version: "3.9"
services:
  postgres_unidade:
    image: postgres:15
    container_name: postgres_unidade
    restart: always
    environment:
      POSTGRES_USER: unidade_user
      POSTGRES_PASSWORD: unidade_pass
      POSTGRES_DB: unidade
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
